### ISSUE TITLE
ARMOR build failed: Could not find it.emarolab.amor:amor:1.0.0.

### ISSUE THREAD

**Issue by chcorbato** [EmaroLab/ros_multi_ontology_references#1]
Hi,

I am trying to install ARMOR in kinetic following the nistructions but i get the following error
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':amor_interface_service:compile'.
> Could not find it.emarolab.amor:amor:1.0.0.
  Searched in the following locations:
      file:/home/chcorbato/mros_ws/devel/share/maven/it/emarolab/amor/amor/1.0.0/amor-1.0.0.pom
      file:/home/chcorbato/mros_ws/devel/share/maven/it/emarolab/amor/amor/1.0.0/amor-1.0.0.jar
      file:/opt/ros/kinetic/share/maven/it/emarolab/amor/amor/1.0.0/amor-1.0.0.pom
      file:/opt/ros/kinetic/share/maven/it/emarolab/amor/amor/1.0.0/amor-1.0.0.jar
      https://github.com/rosjava/rosjava_mvn_repo/raw/master/it/emarolab/amor/amor/1.0.0/amor-1.0.0.pom
      https://github.com/rosjava/rosjava_mvn_repo/raw/master/it/emarolab/amor/amor/1.0.0/amor-1.0.0.jar
      file:/home/chcorbato/.m2/repository/it/emarolab/amor/amor/1.0.0/amor-1.0.0.pom
      file:/home/chcorbato/.m2/repository/it/emarolab/amor/amor/1.0.0/amor-1.0.0.jar
      http://repository.springsource.com/maven/bundles/release/it/emarolab/amor/amor/1.0.0/amor-1.0.0.pom
      http://repository.springsource.com/maven/bundles/release/it/emarolab/amor/amor/1.0.0/amor-1.0.0.jar
      http://repository.springsource.com/maven/bundles/external/it/emarolab/amor/amor/1.0.0/amor-1.0.0.pom
      http://repository.springsource.com/maven/bundles/external/it/emarolab/amor/amor/1.0.0/amor-1.0.0.jar
      https://repo1.maven.org/maven2/it/emarolab/amor/amor/1.0.0/amor-1.0.0.pom
      https://repo1.maven.org/maven2/it/emarolab/amor/amor/1.0.0/amor-1.0.0.jar
  Required by:
      it.emarolab.armor:amor_interface_service:0.1.0
```

**Comment by buoncubi** [comment]
Hi, thank for your feedback.

I did not notice the error because AMORv1.0 was in my maven repository.
The current version of ARMOR should work with AMORv2.2 (that you have cloned from the repository and compiled with `catkin_make`).

I pushed an update that should solve the issue.
Try to re-download and install ARMOR again, and please, let me know if the installation now works also for you.

**Comment by chcorbato** [comment]
Hi,

Thanks for your reply. I have tried again, but now I get an error related to maven (sorry I'm not familiar with it):
```
[ 96%] Built target armor_msgs_generate_messages
Uploading: it/emarolab/amor/amor/2.2.0/amor-2.2.0.jar to repository remote at file:/opt/ros/kinetic/share/maven/
Specified destination directory cannot be created: /opt/ros/kinetic/share/maven/it/emarolab/amor/amor/2.2.0

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':amor:publishMavenJavaPublicationToMavenRepository'.
> Failed to publish publication 'mavenJava' to repository 'maven'
   > Error deploying artifact 'it.emarolab.amor:amor:jar': Error deploying artifact: Specified destination directory cannot be created: /opt/ros/kinetic/share/maven/it/emarolab/amor/amor/2.2.0

```

**Comment by buoncubi** [comment]
With `catkin_make` the compiler should generate the `amor-2.2.0.jar` file in (starting from the root of your workspace) `devel/share/maven/it/emarolab/amor/amor/2.2.0`. 

That is the file that the system does not found because, as stated in your logs, you cannot create it.
It might be a permission issue or a maven setup.

I am not sure if it will fixe the issue, but you can quickly give a try to a *hard* clean of your workspace, i.e.,
- open terminal and `source` your workspace,
- delete the `devel` and `build` folders from the root of the workspace,
- delete all the `build` folder inside  
     -  `src/ros_multi_ontology_references/armor/amor_interface_service`
     - `src/ros_multi_ontology_references/multi_ontology_reference/amor`
- in the terminal above type `catkin_make` 

**PS**: It might be useful to know that the setup for the `jar` generation with `catkin_make` is [this Gradle file](https://github.com/EmaroLab/multi_ontology_reference/blob/1ba2107b4d29e093fd83788f30081d494ad27d63/amor/build.gradle) at the `maven` tag.

**PPS**: The Gradle task that generate the `jar` file is `publishMavenJavaPublicationToMavenRepository` that is set to automatically run with `catkin_make` in [this file](https://github.com/EmaroLab/multi_ontology_reference/blob/1ba2107b4d29e093fd83788f30081d494ad27d63/CMakeLists.txt). 
You could also try to comment it out and run it manually for seeing more logs (probably you need to activate some flags). 
I would try with
- clean the workspace
- `catkin_make` (it might fail)
- `cd src/ros_multi_ontology_references/multi_ontology_reference`
- `./gradlew publishMavenJavaPublicationToMavenRepository`
- `catkin_make`
or
- clean the workspace
- `cd src/ros_multi_ontology_references/multi_ontology_reference`
- `./gradlew`
- `./gradlew publishMavenJavaPublicationToMavenRepository`

**Comment by chcorbato** [comment]
Thanks for following up and explaining.
I have cleaned up my workspace, re-installed ARMOR from scratch and this time there were no issues.
